blank_issues_enabled: false
contact_links:
  - name: Riven Street
    url: mailto:contact@rivenstreet.com
    about: Please contact us directly for urgent issues or private concerns.
  - name: Riven Street LinkedIn
    url: https://www.linkedin.com/company/rivenstreet
    about: Follow us on LinkedIn for updates and announcements.